spring:
  freemarker:
    checkTemplateLocation: false
  datasource:
    url: jdbc:postgresql://localhost:5432/huntercoin
    username: hunter
    password: 4928a569e90bd3fc11b7dcc342d86ce6df67ddf56cb50581721f3b425941aded
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
      jdbc.batch_size: 100
      ordered_inserts: true
      ordered_updates: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.batch_size: 100
      ordered_inserts: true
      ordered_updates: true

chain:
  firstBlockHash:
  firstBlockHeight: 0
  genesisBlock: 00000000db7eb7a9e1a06cf995363dcdc4c28e8ae04827a961942657db9a1631
  blockQuerySize: 1000
  testRun: false
  newRun: true
  runId: -1
  lightRun: true
  hexheaders: false


email:
  to: alexei.zamyatin@yahoo.de
  from: huntercoin.analyzer@sba-research.org
  subject: Huntercoin Analyzer finished execution
  receiver: Alexei Zamyatin
  sender: HuntercoinAnalyzer
  sendMail: true

rest:
  url: http://localhost:8399/rest


jsonrpc:
  host: http://127.0.0.1
  port: 8399
  rpcuser: alexei
  rpcpassword: bf838cdf1288cc64aeeb219672635f7f220ab460da16e68b6b26a19634cd



logging:
  path: /var/log
  file: hunter.log
  level:
    root: INFO
    org.springframwork.web: ERROR
    org.hibernate: ERROR
