spring:
  freemarker:
    checkTemplateLocation: false
  datasource:
    url: jdbc:postgresql://localhost:5432/emercoin
    username: emer
    password: d76827e837f1b94e4ba538666252cd18101f90b56b4f49890587bb86509433c2
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
      jdbc.batch_size: 100
      ordered_inserts: true
      ordered_updates: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.batch_size: 100
      ordered_inserts: true
      ordered_updates: true

server.port: 8003

chain:
  firstBlockHash: 00000000bcccd459d036a588d1008fce8da3754b205736f32ddfd35350e84c2d
  firstBlockHeight: 0
  genesisBlock: 00000000bcccd459d036a588d1008fce8da3754b205736f32ddfd35350e84c2d
  blockQuerySize: 1000
  testRun: false
  runId: -1 # -1 to continue last run, or specify specific run to resume it
  newRun: true
  lightRun: true
  extractNames: false

email:
  to: alexei.zamyatin@yahoo.de
  from: emercoin.analyzer@sba-research.org
  subject: Emercoin Analyzer finished execution
  receiver: Alexei Zamyatin
  sender: EmercoinAnalyzer
  sendMail: true

rest:
    url: http://localhost:6662/rest

jsonrpc:
  host: http://127.0.0.1
  port: 6662
  rpcuser: emercoinrpc
  rpcpassword: BmeQgUxa3LCAHc1hL72qfLwLotU5GLcE9NEkNycZgvqJ

logging:
  path: /var/log
  file: emer.log
  level:
    root: INFO
    org.springframwork.web: ERROR
    org.hibernate: ERROR

